// ─── Teacher Data & Ficha Structure ──────────────────────────────────────────
const TEACHERS = [
  { id: 1, name: "ADNA MARIA CORNELIO" },
  { id: 2, name: "ALESSANDRA SIMONE CARNEIRO SIQUEIRA" },
  { id: 3, name: "ALINE FERREIRA MARIM" },
  { id: 4, name: "ANA PAULA RIGONI MONTEIRO" },
  { id: 5, name: "ANGELITA ALICE SANTOS" },
  { id: 6, name: "ANTONIA NILSETE PEREIRA ALVES" },
  { id: 7, name: "BRUNA SOARES SILVA CAETANO" },
  { id: 8, name: "CAMILA DE FREITAS COSTA REIS" },
  { id: 9, name: "CARINA AMALIA MOREIRA" },
  { id: 10, name: "DANIELE APARECIDA PEREIRA DE SOUZA" },
  { id: 11, name: "DEBORA MARILIA BARAUNA MARIANO" },
  { id: 12, name: "EDIANA MARA PIVETTA" },
  { id: 13, name: "ELIANA CRISTINA DE ALMEIDA" },
  { id: 14, name: "ELIANA MARIA DA SILVA" },
  { id: 15, name: "ELIANE GOMES ANDRADE" },
  { id: 16, name: "ELIZETE DA SILVA PEREIRA" },
  { id: 17, name: "ERICA PAULA PEREIRA" },
  { id: 18, name: "ERIKA DE JESUS CABRAL" },
  { id: 19, name: "FABRICIA CRISTINA DE CARVALHO" },
  { id: 20, name: "FLAVIA MARA DA SILVA" },
  { id: 21, name: "FRANCISCA MARIA DA CONCEICAO SOUZA" },
  { id: 22, name: "GILDETE MARIA PEREIRA" },
  { id: 23, name: "GLAUCIA APARECIDA CALISTA FERREIRA" },
  { id: 24, name: "GRACIELE CRISTINA DE CARVALHO" },
  { id: 25, name: "INILDA ALICE DA SILVA" },
  { id: 26, name: "IRACI MARIA DA SILVA" },
  { id: 27, name: "IRENE MARIA DA SILVA" },
  { id: 28, name: "IZAURA MARIA DA SILVA" },
  { id: 29, name: "JESSICA CRISTINA DA SILVA" },
  { id: 30, name: "JOSEFA MARIA DA SILVA" },
  { id: 31, name: "JULIANA CRISTINA DA SILVA" },
  { id: 32, name: "LEILA CRISTINA DA SILVA" },
  { id: 33, name: "LILIAN CRISTINA DA SILVA" },
  { id: 34, name: "LUCIANA CRISTINA DA SILVA" },
  { id: 35, name: "MARIA CRISTINA DA SILVA" },
  { id: 36, name: "MARIANA CRISTINA DA SILVA" },
  { id: 37, name: "NATALIA CRISTINA DA SILVA" },
  { id: 38, name: "PATRICIA CRISTINA DA SILVA" },
  { id: 39, name: "PRISCILA CRISTINA DA SILVA" },
  { id: 40, name: "RAQUEL CRISTINA DA SILVA" },
  { id: 41, name: "SIMONE CRISTINA DA SILVA" },
  { id: 42, name: "TATIANE CRISTINA DA SILVA" },
  { id: 43, name: "TEREZA CRISTINA DA SILVA" },
  { id: 44, name: "VANESSA CRISTINA DA SILVA" },
  { id: 45, name: "IRACELI FACHETTI" },
  { id: 46, name: "JULIANA MACIEL VIEIRA" },
  { id: 47, name: "MARCIA MARIA DE OLIVEIRA" },
  { id: 48, name: "ELCIA APARECIDA RAMOS" },
  { id: 49, name: "GABRIEL JESUS DA SILVA" },
  { id: 50, name: "GABRIEL ROCHA VIANA" },
  { id: 51, name: "ANGÉLICA DALEPRANE" },
  { id: 52, name: "WALBER HENRIQUE RANGEL PEREIRA" },
  { id: 53, name: "MARIA IZABEL SILVA ZACHARIAS" },
  { id: 54, name: "JULIANA FARIAS GARCIA LEAL" },
  { id: 55, name: "TATIANA CRISTINA AMARAL" },
  { id: 56, name: "THAÍS ANASTÁCIO FARIAS" },
  { id: 57, name: "ANA SILVA DE OLIVEIRA LOBEU" },
  { id: 58, name: "ISTAEL DA SILVA COSTA" },
  { id: 59, name: "DUALCEI GREGORIO BRAGA" },
  { id: 60, name: "JULIANE GUIMARAES DE ANDRADE MILLI" },
  { id: 61, name: "SUELY SANTOS NUNES" },
  { id: 62, name: "GABRIEL FELIPE DE MATOS" },
  { id: 63, name: "ELYKEN DE ALMEIDA MENDONCA SANT ANA" },
  { id: 64, name: "WALDIR AVANCINI JUNIOR" },
  { id: 65, name: "KARLA PALMEZANI CANDIDO" },
  { id: 66, name: "CARLA VIEIRA GODINHO" },
  { id: 67, name: "MARIA ANGELICA CLABUNDE PEREIRA" },
  { id: 68, name: "RONI JOSÉ SOARES" },
  { id: 69, name: "ALINE ARAUJO VAGO GABRIEL" },
  { id: 70, name: "ROSIMERI ZANIBONI" },
  { id: 71, name: "MIGUEL OLIVEIRA BIANCHINI SILVEIRA" },
  { id: 72, name: "ROSILENE ARAUJO DA SILVA" },
  { id: 73, name: "ROBSON LOPES DE OLIVEIRA" },
  { id: 74, name: "MONICA DA COSTA COELHO RIBEIRO" },
  { id: 75, name: "ANGELICA RENATA PRETTI" },
  { id: 76, name: "ADRIANA ALVES DOS SANTOS VELOZO" },
  { id: 77, name: "MARIA BERNADETE MENEGHELLI DE ALMEIDA" },
  { id: 78, name: "CAMILA DOS REIS IGLESIAS" },
  { id: 79, name: "CLAUDIA FALRENE DE CASTRO LOSS" },
  { id: 80, name: "IDILEUZA TEODORO" },
  { id: 81, name: "GISELIA APARECIDA SILVA FERREIRA" },
  { id: 82, name: "THAIS DAMASCENO FELIX BARCELLOS" },
  { id: 83, name: "MARCIA MARIA COZER" },
  { id: 84, name: "JANETE DA CRUZ DE OLIVEIRA" },
  { id: 85, name: "VALERIANA GON GALLON" },
  { id: 86, name: "MARIA DO CARMO SILVA" },
  { id: 87, name: "MARIA CRISTINA DE DEUS SILVA" },
  { id: 88, name: "LUCIANA BROCCO RICATTO" },
  { id: 89, name: "KENIA MARLUCE TESSAROLO" },
  { id: 90, name: "KARLA ANDRESSA RAMOS DE MORAES" },
  { id: 91, name: "JOSIANE CELESTE TOMAZZINI ZENI" },
  { id: 92, name: "JANAINA KEILA DE PAIVA PERTEL COSTA" },
  { id: 93, name: "GLEISYELLE CIBIEN CORRADINI DONADIA" },
  { id: 94, name: "CYNTHIA BINDA" },
  { id: 95, name: "CLAUDIA FABIOLA TEIXEIRA" },
  { id: 96, name: "CARLOS RENATO RAASCH" },
  { id: 97, name: "ANA CLAUDIA DUBBERSTEIN SCHNEIDER" },
  { id: 98, name: "ADRIANA MARIA DALLA BERNARDINA PEREIRA" }
];

const FICHA_FIELDS = {
  pessoal: {
    title: "1 - DADOS PESSOAIS",
    fields: [
      { id: "nomeCompleto", label: "NOME COMPLETO", type: "text" },
      { id: "dataNascimento", label: "Data de Nascimento", type: "text" },
      { id: "naturalidade", label: "Naturalidade", type: "text" },
      { id: "cor", label: "Cor", type: "text" },
      { id: "cpf", label: "CPF", type: "text" },
      { id: "rg", label: "Identidade", type: "text" },
      { id: "rgEmissor", label: "Órg. Emissor", type: "text" },
      { id: "rgExpedicao", label: "Data Expedição", type: "text" },
      { id: "ctpsNumero", label: "CTPS Nº", type: "text" },
      { id: "ctpsSerie", label: "Série", type: "text" },
      { id: "tituloEleitoral", label: "Título Eleitoral", type: "text" },
      { id: "pisPasep", label: "PIS/PASEP", type: "text" },
      { id: "cargoContraCheque", label: "Cargo", type: "text" },
      { id: "matriculaFuncional", label: "Matrícula", type: "text" },
      { id: "nomeMae", label: "Mãe", type: "text" },
      { id: "nomePai", label: "Pai", type: "text" },
      { id: "enderecoRua", label: "Rua", type: "text" },
      { id: "enderecoNum", label: "Nº", type: "text" },
      { id: "enderecoApt", label: "Aptº", type: "text" },
      { id: "enderecoBairro", label: "Bairro", type: "text" },
      { id: "cep", label: "CEP", type: "text" },
      { id: "telefone", label: "Tel Fixo", type: "text" },
      { id: "telefoneCelular", label: "Celular", type: "text" },
      { id: "email", label: "e-mail", type: "text" },
    ]
  },
  atuacao: {
    title: "2 - ÁREA DE ATUAÇÃO",
    fields: [
      { id: "anosIniciaisEF", label: "Anos Iniciais", type: "checkbox" },
      { id: "anosIniciaisDisc", label: "Disciplina (Iniciais)", type: "text" },
      { id: "anosFinaisEF", label: "Anos Finais", type: "checkbox" },
      { id: "anosFinaisDisc", label: "Disciplina (Finais)", type: "text" },
      { id: "administrativo", label: "Administrativo", type: "checkbox" },
      { id: "administrativoDesc", label: "Desc. Adm", type: "text" },
      { id: "turnoTrabalho", label: "Turno", type: "text" },
    ]
  },
  situacaoFuncional: {
    title: "3 - SITUAÇÃO FUNCIONAL",
    fields: [
      { id: "sfEstagiario", label: "Estagiário", type: "checkbox" },
      { id: "sfEstagiarioCH", label: "CH Estagiário", type: "text" },
      { id: "sfDTPMC1", label: "DT PMC (1)", type: "checkbox" },
      { id: "sfDTPMC_Disc1", label: "Disc. DT 1", type: "text" },
      { id: "sfDTPMC_CH1", label: "CH DT 1", type: "text" },
      { id: "sfLocalizado", label: "Localizado", type: "checkbox" },
      { id: "sfLocalizadoDisc", label: "Disc. Localizado", type: "text" },
      { id: "sfLocalizadoCH", label: "CH Localizado", type: "text" },
      { id: "sfEscolaOrigem", label: "Escola Origem", type: "text" },
      { id: "sfEfetivoPMC", label: "Efetivo PMC", type: "checkbox" },
      { id: "sfEstatutario", label: "Estatutário", type: "checkbox" },
      { id: "sfCeletista", label: "Celetista", type: "checkbox" },
      { id: "sfEfetivoPMC_Disc", label: "Disc. Efetivo", type: "text" },
      { id: "sfEfetivoPMC_CH", label: "CH Efetivo", type: "text" },
      { id: "sfEfetivoSEDU", label: "Efetivo SEDU", type: "checkbox" },
      { id: "sfEfetivoSEDU_Disc", label: "Disc. SEDU", type: "text" },
      { id: "sfEfetivoSEDU_CH", label: "CH SEDU", type: "text" },
      { id: "sfDTPMC2", label: "DT PMC (2)", type: "checkbox" },
      { id: "sfDTPMC_Disc2", label: "Disc. DT 2", type: "text" },
      { id: "sfDTPMC_CH2", label: "CH DT 2", type: "text" },
      { id: "sfEscolaComp1", label: "Escola Comp. 1", type: "text" },
      { id: "sfEscolaComp1CH", label: "CH Comp. 1", type: "text" },
      { id: "sfEscolaComp2", label: "Escola Comp. 2", type: "text" },
      { id: "sfEscolaComp2CH", label: "CH Comp. 2", type: "text" },
    ]
  },
  escolarizacao: {
    title: "4 - FORMAÇÃO ACADÊMICA",
    fields: [
      { id: "ensinoMedio", label: "Ensino Médio", type: "text" },
      { id: "estudosAdicionais", label: "Estudos Adicionais", type: "text" },
      { id: "cursoSuperiorConcluido", label: "Superior Concluído", type: "text" },
      { id: "superiorConcluidoInicio", label: "Início", type: "text" },
      { id: "superiorConcluidoFim", label: "Conclusão", type: "text" },
      { id: "superiorConcluidoInstTipo", label: "Tipo Inst.", type: "text" },
      { id: "superiorConcluidoInstNome", label: "Instituição", type: "text" },
      { id: "cursoSuperiorAndamento", label: "Superior Andamento", type: "text" },
      { id: "superiorAndamentoInicio", label: "Início", type: "text" },
      { id: "superiorAndamentoInstTipo", label: "Tipo Inst.", type: "text" },
      { id: "superiorAndamentoInstNome", label: "Instituição", type: "text" },
      { id: "posGradStatus", label: "Status Pós", type: "text" },
      { id: "especializacao", label: "Especialização", type: "text" },
      { id: "especializacaoConclusao", label: "Conclusão Esp.", type: "text" },
      { id: "mestrado", label: "Mestrado", type: "text" },
      { id: "mestradoConclusao", label: "Conclusão Mes.", type: "text" },
      { id: "doutorado", label: "Doutorado", type: "text" },
      { id: "doutradoConclusao", label: "Conclusão Dou.", type: "text" },
    ]
  },
  formacaoContinuada: {
    title: "5 - OUTROS CURSOS",
    fields: [
      { id: "fcCreche", label: "Creche", type: "checkbox" },
      { id: "fcAnosFinais", label: "Anos Finais", type: "checkbox" },
      { id: "fcAnosIniciais", label: "Anos Iniciais", type: "checkbox" },
      { id: "fcEdEspecial", label: "Ed. Especial", type: "checkbox" },
      { id: "fcEdAmbiental", label: "Ed. Ambiental", type: "checkbox" },
      { id: "fcPreEscola", label: "Pré-Escola", type: "checkbox" },
      { id: "fcEnsinoMedio", label: "Ensino Médio", type: "checkbox" },
      { id: "fcEdIndigena", label: "Ed. Indígena", type: "checkbox" },
      { id: "fcDirHumanos", label: "Direitos Humanos", type: "checkbox" },
      { id: "fcRelacoes", label: "Rel. Étnico-Raciais", type: "checkbox" },
      { id: "fcEJA", label: "EJA", type: "checkbox" },
      { id: "fcEdCampo", label: "Ed. Campo", type: "checkbox" },
      { id: "fcGenero", label: "Gênero/Div. Sexual", type: "checkbox" },
      { id: "fcOutros", label: "Outros", type: "checkbox" },
      { id: "fcNenhum", label: "Nenhum", type: "checkbox" },
    ]
  }
};

function getTeacherById(id) {
  return TEACHERS.find(t => t.id === parseInt(id));
}

const REQUIRED_DOCS = [
  { id: "rg", label: "RG (Frente e Verso)" },
  { id: "cpf", label: "CPF" },
  { id: "comprovante", label: "Comprovante de Residência" },
  { id: "diploma", label: "Diploma/Certificado de Escolaridade" },
  { id: "foto", label: "Foto 3x4" },
  { id: "antecedentes", label: "Certidão de Antecedentes Criminais" },
  { id: "outros", label: "Outros Documentos" },
];
